# Generated by Django 5.2.8 on 2025-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor')], max_length=10, null=True),
        ),
    ]
