# Generated by Django 5.2.8 on 2026-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
