# Generated by Django 5.2.8 on 2026-01-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='call_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='review_done',
            field=models.BooleanField(default=False),
        ),
    ]
