# Generated by Django 5.2.8 on 2026-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
