# Generated by Django 5.2.8 on 2026-01-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendance_cancelled_at'),
        ('api', '0003_payment_created_at'),
    ]

    operations = [
    ]
