# Generated by Django 5.2.8 on 2025-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lesson_date_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.CharField(blank=True, choices=[('OSNOVNA', 'Osnovna škola'), ('SREDNJA', 'Srednja škola')], max_length=20, null=True),
        ),
    ]
