# Generated by Django 5.2.8 on 2025-11-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lesson_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='instructor',
            new_name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
