# Generated by Django 5.2.8 on 2025-11-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lesson_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.student'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='attendance',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.attendance'),
        ),
    ]
