# Generated by Django 6.0 on 2025-12-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lesson_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='subject',
        ),
        migrations.AddField(
            model_name='instructor',
            name='sujects',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='api.subject'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
