# Generated by Django 5.2.8 on 2025-11-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_payment_instructor_remove_payment_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attendance'),
        ),
    ]
