# Generated by Django 5.2.8 on 2025-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_instructor_video_url_alter_instructor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='api.subject'),
        ),
    ]
