# Generated by Django 5.2.8 on 2025-12-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_instructor_subject_instructor_sujects_and_more'),
        ('api', '0010_remove_instructor_subject_instructor_subjects'),
    ]

    operations = [
    ]
