# Generated by Django 5.2.8 on 2025-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_merge_20251221_2034"),
    ]

    operations = [
        # 1) Instructor.subject -> makni iz state-a, a u bazi dropaj kolonu ako postoji
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_instructor DROP COLUMN IF EXISTS subject_id;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="instructor",
                    name="subject",
                ),
            ],
        ),

        # 2) Lesson.status -> dodaj u bazu samo ako ne postoji, a u state-u dodaj field
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE api_lesson "
                        "ADD COLUMN IF NOT EXISTS status varchar(10) NOT NULL DEFAULT 'ACTIVE';"
                    ),
                    reverse_sql="ALTER TABLE api_lesson DROP COLUMN IF EXISTS status;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="lesson",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("ACTIVE", "Aktivan"),
                            ("EXPIRED", "Istekao"),
                            ("CANCELED", "Otkazan"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
            ],
        ),

        # 3) Student.learning_goals -> dodaj ako ne postoji
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_student ADD COLUMN IF NOT EXISTS learning_goals text NULL;",
                    reverse_sql="ALTER TABLE api_student DROP COLUMN IF EXISTS learning_goals;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="student",
                    name="learning_goals",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),

        # 4) Student.preferred_times -> jsonb, NOT NULL default []
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE api_student "
                        "ADD COLUMN IF NOT EXISTS preferred_times jsonb NOT NULL DEFAULT '[]'::jsonb;"
                    ),
                    reverse_sql="ALTER TABLE api_student DROP COLUMN IF EXISTS preferred_times;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="student",
                    name="preferred_times",
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
    ]
