# Generated by Django 5.2.8 on 2025-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20251222_1009'),
    ]

    operations = [

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.RemoveField(
                model_name='instructor',
                name='subjects',
            ),
        ],
    ),

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AddField(
                model_name="lesson",
                name="status",
                field=models.CharField(
                    choices=[
                        ('ACTIVE', 'Aktivan'),
                        ('EXPIRED', 'Istekao'),
                        ('CANCELED', 'Otkazan'),
                    ],
                    default='ACTIVE',
                    max_length=10,
                ),
            ),
        ],
    ),

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AddField(
                model_name='student',
                name='favorite_instructors',
                field=models.ManyToManyField(
                    blank=True,
                    related_name='favorited_by',
                    to='api.instructor',
                ),
            ),
        ],
    ),

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AddField(
                model_name='student',
                name='learning_goals',
                field=models.TextField(blank=True, null=True),
            ),
        ],
    ),

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AddField(
                model_name='student',
                name='notifications_enabled',
                field=models.BooleanField(default=False),
            ),
        ],
    ),

    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.AddField(
                model_name='student',
                name='preferred_times',
                field=models.JSONField(blank=True, default=list),
            ),
        ],
    ),
]
