# Generated by Django 5.2.8 on 2025-12-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_instructor_sujects_lesson_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[],
        ),
    ]

