# Generated by Django 5.2.8 on 2025-12-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_sujects_instructor_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='knowledge_level',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
