# Generated by Django 5.2.8 on 2026-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_student_knowledge_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFavoriteInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'api_student_favorite_instructors',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
