# Generated by Django 5.2.8 on 2026-01-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_studentfavoriteinstructor_student_school_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFavoriteInstructor',
        ),
    ]
