# Generated by Django 5.2.8 on 2026-01-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_instructor_subject_lesson_status_and_more'),
        ('api', '0016_delete_studentfavoriteinstructor'),
    ]

    operations = [
    ]
