# Generated by Django 5.2.8 on 2026-01-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260106_2246'),
    ]

    operations = [
    migrations.AlterUniqueTogether(
        name='attendance',
        unique_together={('lesson', 'student')},
    ),
]
