# Generated by Django 5.2.8 on 2026-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260105_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
