# Generated by Django 5.2.8 on 2026-01-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_instructor_lat_instructor_lng_instructor_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='api.subject'),
        ),
    ]
