# Generated by Django 5.2.8 on 2026-01-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_instructor_subjects_alter_attendance_unique_together'),
        ('api', '0019_instructor_subjects'),
    ]

    operations = [
    ]
