# Generated by Django 5.2.8 on 2026-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20260107_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
