# Generated by Django 5.2.8 on 2026-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_attendance_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
