# Generated by Django 5.2.8 on 2026-01-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_attendance_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
