# Generated by Django 5.2.8 on 2026-01-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_instructor_profile_image_url_and_more'),
        ('api', '0022_lesson_jitsi_room'),
    ]

    operations = [
    ]
