# Generated by Django 5.2.8 on 2026-01-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20260112_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='google_calendar_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
