# Generated by Django 5.2.8 on 2026-01-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20260112_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
