# Generated by Django 5.2.8 on 2026-01-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_attendance_reminder_1h_sent'),
        ('api', '0024_remove_question_answer_question_correct_answer_and_more'),
    ]

    operations = [
    ]
