# Generated by Django 5.2.8 on 2026-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260114_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email_pending',
            field=models.BooleanField(default=False),
        ),
    ]
