# Generated by Django 5.2.8 on 2026-01-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260114_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='notes',
        ),
        migrations.AddField(
            model_name='summary',
            name='file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.lesson'),
        ),
    ]
